### ISSUE TITLE
Issue with rewriting zipfile

### ISSUE THREAD

**Issue by Peter9192** [i-VRESSE/bartended-haddock3#25]
I tried submitting a haddock3 job through the bartended-haddock frontend. However, it keeps on failing with an error message from within the zip library:

```error
TypeError: First parameter has member 'readable' that is not a ReadableStream.
    at assertReadableStream (/home/peter/ivresse/bartended-haddock3/node_modules/web-streams-polyfill/src/lib/validators/readable-stream.ts:5:11)
    at convertReadableWritablePair (/home/peter/ivresse/bartended-haddock3/node_modules/web-streams-polyfill/src/lib/validators/readable-writable-pair.ts:15:3)
    at ReadableStream.pipeThrough (/home/peter/ivresse/bartended-haddock3/node_modules/web-streams-polyfill/src/lib/readable-stream.ts:211:23)
    at new CodecWorker (/home/peter/ivresse/bartended-haddock3/node_modules/@zip.js/zip.js/index.cjs:7189:23)
    at runWorker (/home/peter/ivresse/bartended-haddock3/node_modules/@zip.js/zip.js/index.cjs:7497:12)
    at ZipEntry$1.getData (/home/peter/ivresse/bartended-haddock3/node_modules/@zip.js/zip.js/index.cjs:8765:27)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Reader.init (/home/peter/ivresse/bartended-haddock3/node_modules/@zip.js/zip.js/index.cjs:10558:17)
    at initStream (/home/peter/ivresse/bartended-haddock3/node_modules/@zip.js/zip.js/index.cjs:8238:3)
    at async Promise.all (index 0)
```

I narrowed down the source of the issue to the `getText` call in  `rewriteConfigInArchive` function:
https://github.com/i-VRESSE/bartended-haddock3/blob/b142153d60371d38fa35f4fc83bb3855f5ad4ed9/app/models/applicaton.server.ts#L93

but from there I'm a bit lost.

**Comment by sverhoeven** [comment]
The test suite works, I expected remix to also work.
Seems the remix environment is different from the vitest environment. 
Looks like remix is using a incompatible web-streams-polyfill.
